---
- name: Backup PostgreSQL database
  hosts: database_servers
  become: yes
  vars:
    db_name: your_database_name
    db_user: your_db_user
    db_password: your_db_password
    backup_path: /path/to/backup/directory

  tasks:
    - name: Install PostgreSQL client
      apt:
        name: postgresql-client
        state: present
      when: ansible_os_family == "Debian"

    - name: Create backup directory
      file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'

    - name: Backup PostgreSQL database
      command: >
        pg_dump -U {{ db_user }} -F c -b -v -f {{ backup_path }}/{{ db_name }}_{{ ansible_date_time.date }}.backup {{ db_name }}
      environment:
        PGPASSWORD: "{{ db_password }}"